# Generated by Django 5.2.5 on 2025-08-16 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Poyabzallar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(max_length=100)),
                ('size', models.PositiveIntegerField()),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, default='default/poyabzal.png', null=True, upload_to='poyabzallar-media/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('made_country', models.CharField(max_length=50)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
        ),
    ]
